// <auto-generated />
using DelFood.Web.ProductAPI.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DelFood.Web.ProductAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20221024153426_SeedProducts")]
    partial class SeedProducts
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("DelFood.Web.ProductAPI.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"), 1L, 1);

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            CategoryName = "Appetizer",
                            Description = "Some description about greate food!",
                            ImageUrl = "E:\\Work\\Delivery-Food-API-Application\\DelFood.Web\\wwwroot\\Images\\Shrimp.jpg",
                            Name = "Shrimp in tom-yam sauce",
                            Price = 14.99
                        },
                        new
                        {
                            ProductId = 2,
                            CategoryName = "Salads",
                            Description = "Some description about tasty food!",
                            ImageUrl = "E:\\Work\\Delivery-Food-API-Application\\DelFood.Web\\wwwroot\\Images\\Tuna salad.jpg",
                            Name = "Tuna Salad",
                            Price = 11.99
                        },
                        new
                        {
                            ProductId = 3,
                            CategoryName = "Dessert",
                            Description = "Some description about tasty food!",
                            ImageUrl = "E:\\Work\\Delivery-Food-API-Application\\DelFood.Web\\wwwroot\\Images\\Sweet pie.jpg",
                            Name = "Sweet Pie",
                            Price = 10.99
                        },
                        new
                        {
                            ProductId = 4,
                            CategoryName = "Entree",
                            Description = "Some description about tasty food!",
                            ImageUrl = "E:\\Work\\Delivery-Food-API-Application\\DelFood.Web\\wwwroot\\Images\\Steak.jpg",
                            Name = "Striploin steake with Dor blue cheese butter",
                            Price = 19.989999999999998
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
